### ISSUE TITLE
How to handle frames with no face

### ISSUE THREAD

**Issue by Lalithaditya2004** [uygarkurt/video-retalking#1]
When there is no face in some frames in video, how to handle that situation.  I am working on a intern project and I am new to this niche. I was just wondering if it is possible for the frames with no face to just apply the audio instead of throwing me a No face detected error.

**Comment by Lalithaditya2004** [comment]
I had seen wav2lip had made some changes to settle this issue , is there any way to handle the situation here too?

**Comment by uygarkurt** [comment]
I'm not sure if we can directly do it with this package. However you can follow a 2 step approach. Maybe detect the frames first which has faces, then apply this to those frames. Skip the other frames.

**Comment by Lalithaditya2004** [comment]
Ok thanks can you mention the files(and functions) on which the work is to be done. There are just too many files and I don't understand most of them.
